- hosts: localhost
  tasks:
    - name: Remove Prometheus Chart if exists
      raw: helm delete --purge prometheus  || true 

    - name: Install Prometheus Chart based on values at {{ prometheus_config_file }} 
      raw: helm install --name prometheus stable/prometheus --values  {{ prometheus_config_file }}
    
