- hosts: localhost
  tasks:
    - name: Remove Prometheus Chart if exists
      raw: helm delete --purge prometheus  || true 

    - name: Remove PV
      raw: kubectl delete -f storage/create_pv_nfs.yaml --wait || true

    - name: Create PV
      raw: kubectl apply -f storage/create_pv_nfs.yaml --wait

    - name: Install Prometheus Chart based on values at {{ prometheus_config_file }} 
      raw: helm install --name prometheus stable/prometheus --values  {{ prometheus_config_file }}
    
