- hosts: localhost
  connection: local
  tasks:
    - name: Fix host kernel modules
      lineinfile:
        line: "overlay"
        dest: "/etc/modules"
      
    - name: Creating LXD containers
      loop: "{{ groups['k8s_lxc'] }}"
      lxd_container:
        name: "{{ item }}"
        state: started
        config:
          limits.cpu: "{{ hostvars[item].numcpu }}"
          limits.memory: 8GB
          limits.memory.swap: "false"
          linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,br_netfilter,bridge
          raw.lxc: "lxc.apparmor.profile=unconfined\nlxc.cap.drop= \nlxc.cgroup.devices.allow=a\nlxc.mount.auto=proc:rw sys:rw cgroup:rw"
          security.nesting: "true"
          security.privileged: "true"
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams
          alias: bionic/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
      tags:
        - lxc

- hosts: k8s_lxc
  gather_facts: yes
  become: true
  tasks:
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Set password to user Ubuntu
      user:
        name: ubuntu
        password: "{{ ubuntu_password_hash }}"
        update_password: always
      no_log: true
      tags:
        - change_password

    - name: Enable ssh password auth
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'

    - name: Reload sshd server
      systemd:
        name: sshd
        state: reloaded

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      tags:
        - k8s_update

    - name: Install Additional Packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - curl
          - wget
          - thin-provisioning-tools
          - lvm2
          - software-properties-common
          - net-tools
          - sudo
          - sshpass
          - less
          - nfs-common

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable and start services docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add Kubernetes APT GPG Key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes APT Repository
      apt_repository:
        repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
        state: present
        update_cache: yes

    - name: Install Kubernetes (kubeadm, kubelet, kubectl)
      apt:
        name: "{{ kubernetes }}"
        update_cache: yes
        cache_valid_time: 3600
        state: present
        force: yes
      vars:
        kubernetes:
          - kubeadm={{ k8s_version }}
          - kubelet={{ k8s_version }}
          - kubectl={{ k8s_version }}

    - name: Modify cgroup-driver to systemd for Kubelet
      shell: echo "KUBELET_CGROUP_ARGS=--cgroup-driver=systemd" > /etc/default/kubelet
      
    - name: Enable and start Kubelet service
      systemd:
        name: kubelet
        state: restarted
        enabled: yes

    - name: Add ubuntu user to sudoers with NOPASSWD flag
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Group docker added to user ubuntu
      user:
        user: ubuntu
        groups: docker
        append: yes


- hosts: masters
  gather_facts: yes
  become_user: ubuntu
  become: true
  tasks:
    - name: Pulling Kubernetes Images
      shell: sudo kubeadm config images pull --kubernetes-version {{ k8s_version.split("-")[0] }}
      tags:
        - skip_ansible_lint
        - master_setup

    - name: Initializing the Kubernetes cluster
      shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 {{ kubeadm_args }} > ~/kubeinit.log
      tags:
        - skip_ansible_lint
        - master_setup

    - name: Create ~/.kube directory if not exists
      file:
        path: ~/.kube
        state: directory

    - name: Copy Kube admin config to home directory
      become: true
      become_user: root
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes

    - name: Deploy flannel network
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      tags:
        - skip_ansible_lint

    - name: Generate Cluster join command
      shell: |
        joinCommand=$(kubeadm token create --print-join-command)  
        echo "$joinCommand {{ kubeadm_args }}" > ~/joincluster.sh
      tags:
        - skip_ansible_lint

    - name: Get Helm manifest
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get
        dest: ~/./get.helm.sh
      tags:
        - skip_ansible_lint

    - name: Install Helm
      shell: bash ~/./get.helm.sh
      tags:
        - skip_ansible_lint

    - name: Remove Helm manifest
      file:
        path: ~/./get.helm.sh
        state: absent

    - name: Create Helm ServiceAccount
      shell: kubectl create serviceaccount tiller --namespace=kube-system
      tags:
        - skip_ansible_lint

    - name: Create Helm Roles
      shell: kubectl create clusterrolebinding tiller-admin --serviceaccount=kube-system:tiller --clusterrole=cluster-admin
      tags:
        - skip_ansible_lint

    - name: Init helm
      shell: helm init --service-account=tiller
      tags:
        - skip_ansible_lint

    - name: Enable Dashboard Token
      shell: kubectl create clusterrolebinding kubernetes-dashboard -n kube-system --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard
      tags:
        - skip_ansible_lint

- hosts: nodes
  gather_facts: yes
  become_user: ubuntu
  become: true
  tasks:
    - name: Join worker nodes to the Kubernetes cluster
      shell: |
        sshpass -p {{ ubuntu_password }} scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@k8s-master.lxd:~/joincluster.sh ~/joincluster.sh 2>/tmp/joincluster.log
        sudo bash /home/ubuntu/joincluster.sh >> /tmp/joincluster.log
      tags:
        - skip_ansible_lint
        - join_cluster

- hosts: localhost
  tasks:
    - name: Copy k8s admin.conf to ~/.kube/config
      shell: lxc file pull k8s-master/etc/kubernetes/admin.conf ~/.kube/config
      tags:
        - skip_ansible_lint

    - name: Deploy Kubernetes Dashboard
      shell: kubectl apply -f deploy/dashboard.yaml
      tags:
        - skip_ansible_lint

    - name: Grant full admin privileges to Dashboard Service Account
      shell: kubectl apply -f deploy/authentication.yaml
      tags:
        - skip_ansible_lint
