apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /
    server: 10.244.1.110 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
