apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /
    server: 10.96.0.2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-storage

#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: grafana-pvc
#spec:
#  accessModes:
#  - ReadWriteMany
#  storageClassName: grafana-storage
#  resources:
#    requests:
#      storage: 20Gi
      