apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /
    server: 10.96.0.2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-storage
  
---

#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: jenkins
#spec:
#  accessModes:
#  - ReadWriteMany
#  storageClassName: jenkins-storage
#  resources:
#    requests:
#      storage: 10Gi
      